<a href="https://colab.research.google.com/github/fatimascode/PyTorchTutorials/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import torch
import torch.nn as nn
print(f'Python version info: {sys.version}')
print(f'PyTorch version info: {torch.__version__}')

# Import pprint, module we use for making our print statements prettier
import pprint
pp = pprint.PrettyPrinter()

Python version info: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
PyTorch version info: 2.2.1+cu121


In [2]:
import numpy as np

**LISTS**

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.79065153, 0.02158878, 0.16888321, 0.75165811],
       [0.82659709, 0.02742938, 0.70654976, 0.50670704],
       [0.88403562, 0.80565566, 0.34516725, 0.769306  ]])

TENSOR

In [8]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 1.0159,  1.2359, -0.6180, -0.9792],
        [-0.1132, -0.8650,  1.2981, -0.8851],
        [ 0.7031,  1.6537, -0.7691, -1.8899]])

In [9]:
  tensor_from_numpy = torch.tensor(np1)
  tensor_from_numpy

tensor([[0.7907, 0.0216, 0.1689, 0.7517],
        [0.8266, 0.0274, 0.7065, 0.5067],
        [0.8840, 0.8057, 0.3452, 0.7693]], dtype=torch.float64)